spring.application.name=ems-backend
# 1. Database Connection URL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ems}

# 2. Database Username & Password
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

# 3. MySQL Driver Class
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. Hibernate DDL Auto (Schema Generation Strategy)
spring.jpa.hibernate.ddl-auto=update

# 5. Show SQL Queries in Console
spring.jpa.show-sql=true